### ISSUE TITLE
Literate vs Weave

### ISSUE THREAD

**Issue by blegat** [jump-dev/JuMPTutorials.jl#31]
I was wondering, what is the difference between https://github.com/JunoLab/Weave.jl and https://github.com/fredrikekre/Literate.jl and what makes Weave more appropriate for this project ?

**Comment by barpit20** [comment]
Both of them are literate programming packages. The major differences that I see between them are 

- Weave supports output to PDFs and webpages while Literate does not. However, we don't use these two output formats for our package as they don't work very well.
- Literate supports chunk options for notebooks while Weave does not. This is something which will make writing tests even easier than it is right now.
- There is a bug in Weave due to which plots don't work when converting to Jupyter notebooks. This is something that should be resolved in the future. No such issue seems to be there with Literate.

Literate may be slightly better for our use case because of the second point but I don't think it's worth rewriting the whole package.

**Comment by chriscoey** [comment]
Which of the two seems to be under more active development slash seems like it might have a longer life?

Agreed that it's probably not worth rewriting, unless it's more a matter of find-replace.

**Comment by barpit20** [comment]
Weave is older due to which it has more contributors and users. It is also now under JunoLab so it might have a longer life. In case we want to switch though, it's not a matter of find-replace and will take 4-5 days.

I think it only makes sense to put in the effort to switch if we start having issues with Weave.

**Comment by matbesancon** [comment]
Weave seems to be working fine, even 6 months after this conversation, we can keep it as is for now
