### ISSUE TITLE
remove Manifest.toml (add to .gitignore)

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/JuMPTutorials.jl#41]
Other packages (JuMP, MOI, Dualization etc) don't commit Manifest.toml, only Project.toml.
You can see the .gitignore of these packages.

**Comment by KristofferC** [comment]
For a set of tutorials I think it is very good to have a Manifest checked in so that you know that the users running the tutorial are running on the same version of the packages as the tutorial was created. This project also has zero `[compat]` entries so the tutorials here will definitely stop working as soon as any of the dependencies make a breaking change.

**Comment by matbesancon** [comment]
@chriscoey I added some compat bounds on Project toml on the "essential" dependencies of the project, so that we can keep manifest and `up` it without breaking (if all goes well)

**Comment by cbdavis** [comment]
I'm not able to run the notebooks with IJulia (I get a dead kernel) unless I remove the Manifest.toml file.  I've seen this with Julia 1.4.2 on both Windows 10 and Ubuntu 20.04.

**Comment by matbesancon** [comment]
the manifest is run with Julia 1.0 normally to ensure compatibility with the LTS

**Comment by odow** [comment]
Closing as fixed.
