### ISSUE TITLE
add various build status and coverage badges?

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/JuMPTutorials.jl#42]
like https://github.com/JuliaOpt/Dualization.jl

**Comment by barpit20** [comment]
The build and documentation badges are already present. I'll also add the social badges so that people know where to ask more questions.

Since these are tutorial files and not regular code, I am unsure if adding coverage makes sense. We will probably not be having package versions either so only a dev docs link is enough in my opinion. What do you think?

**Comment by odow** [comment]
The build badge points to your private repo. So it currently shows nothing. (See #43.)

**Comment by odow** [comment]
Closing as fixed.
