### ISSUE TITLE
remove misc files?

### ISSUE THREAD

**Issue by chriscoey** [jump-dev/JuMPTutorials.jl#5]
since this isn't really a Julia "package", but rather a repo for tutorials, would it make sense to reduce clutter and remove `src` and `test` folders and other unnecessary files that were autogenerated?

**Comment by chriscoey** [comment]
also if there are to be no tests in the package, then Travis can be deactivated and the build badge removed on the readme

**Comment by barpit20** [comment]
The idea was to have the Weave.jl utilities specific to JuMP in the `src` folder and create a package so that the notebooks can be accessed easily from within Julia. I plan on adding the tests this week hence the Travis badge.

Should I delete the `docs` folder? I had kept it in case we want to have any additional information there. I can remove it for now and add it back if needed.

**Comment by chriscoey** [comment]
Ok makes sense. Yeah if you don't currently have a solid plan for the docs folder, delete it just to keep things simple
